# syntax=docker/dockerfile:1

## Build
FROM golang:1.16-buster AS build

WORKDIR /app

#COPY go.mod ./
#COPY go.sum ./
#RUN go mod download

COPY src ./

RUN go build -o /comedproxy

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /docker /comedproxy

# discovery
EXPOSE 18830

# proxy
EXPOSE 18888



USER nonroot:nonroot

ENTRYPOINT ["/comedproxy"]
